---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: qcore
# description will be included in the image's metadata
description: "ucore + additions"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: script
    snippets:
    - "$CONFIG_DIRECTORY/scripts/setup-periphery.py --force-systemd --distro-install"
    - |
        firewall-offline-cmd --new-service=periphery
        firewall-offline-cmd --service=periphery --set-description="Komodo Periphery"
        firewall-offline-cmd --service=periphery --add-port=8120/tcp

  - type: systemd
    system:
      enabled:
        - periphery

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - qemu-guest-agent
    remove: []
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      #- firefox
      #- firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: systemd
    system:
      enabled:
        - qemu-guest-agent
        - docker.service
        - docker.socket


  - type: signing # this sets up the proper policy & signing files for signed images to work fully
